[project]
name = "iconeval"
version = "1.0.0"
description = "Convenient evaluation of ICON model output with ESMValTool"
authors = [
    {name = "Manuel Schlund", email = "manuel.schlund@dlr.de"},
    {name = "Lisa Bock", email = "lisa.bock@dlr.de"},
]
readme = "README.md"
requires-python = ">=3.12"
keywords = ["ICON", "ESMValTool", "Earth System Model Evaluation"]
license = {file = "LICENSE"}
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "esmvaltool",
    "fire",
    "loguru",
    "python-swiftclient",
    "pyyaml",
    "requests",
]

[project.scripts]
iconeval = "iconeval.main:main"
publish_html = "iconeval.output_handling.publish_html:main"


[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tool.pixi.dependencies]
fire = "*"
loguru = "*"
python = ">=3.12"
python-swiftclient = "*"
pyyaml = "*"
requests = "*"

[tool.pixi.pypi-dependencies]
iconeval = { path = ".", editable = true }

[tool.pixi.environments]
default = { features= ["esmvaltool", "dev", "test"], solve-group = "default" }
esmvaltool-dev = { features= ["esmvaltool-dev", "dev", "test"], solve-group = "esmvaltool-dev" }
test-py312 = { features = ["esmvaltool", "py312", "test"], solve-group = "py312" }
test-py313 = { features = ["esmvaltool", "py313", "test"], solve-group = "py313" }
test-py314 = { features = ["esmvaltool", "py314", "test"], solve-group = "py314" }

[tool.pixi.feature.dev.dependencies]
pre-commit = "*"
py-markdown-table = "*"

[tool.pixi.feature.esmvaltool.dependencies]
esmvalcore = ">=2.15.0"
esmvaltool-base = ">=2.15.0"
# Additional dependencies needed by the ESMValTool diagnostics we use (the
# strategy here is to use esmvaltool-base + few explicit dependencies instead
# of the full esmvaltool-python to keep the environment slim)
seaborn = "*"
scikit-learn = ">=1.4.0"
mapgenerator = ">=1.0.5"

# Ensure that all dependencies of esmvalcore and esmvaltool-base are installed
# from conda-forge, not PyPI
[tool.pixi.feature.esmvaltool-dev.dependencies]
# esmvalcore
aiohttp = "*"
cartopy = "*"
cf-units = "*"
cftime = "*"
dask = ">=2025"
dask-jobqueue = "*"
distributed = "*"
esgf-pyclient = ">=0.3.1"
filelock = "*"
fiona = "*"
fire = "*"
geopy = "*"
humanfriendly = "*"
intake-esgf = ">=2026.4.28"
iris = "<3.16"
iris-esmf-regrid = ">=0.11.0"
iris-grib = ">=0.20.0"
isodate = ">=0.7.0"
jinja2 = "*"
libnetcdf = "!=4.9.1"
nc-time-axis = "*"
ncdata = "*"
nested-lookup = "*"
netcdf4 = "*"
numpy = "!=1.24.3"
packaging = "*"
pandas = "*"
pillow = "*"
pip = "!=21.3"
prov = "*"
psutil = "*"
py-cordex = "*"
pybtex = "*"
python = ">=3.12"
python-stratify = ">=0.3"
pyyaml = "*"
requests = "*"
rich = "*"
scipy = ">=1.6"
shapely = ">=2.0.0"
xarray = "*"
yamale = "*"
zarr = ">3"
# esmvaltool-base
matplotlib-base = "*"
# Additional ESMValTool dependencies we need because of the diagnostics we use
seaborn = "*"
scikit-learn = ">=1.4.0"
mapgenerator = ">=1.0.5"

[tool.pixi.feature.esmvaltool-dev.pypi-dependencies]
esmvalcore = { git = "https://github.com/ESMValGroup/ESMValCore.git", branch = "main" }
esmvaltool = { git = "https://github.com/ESMValGroup/ESMValTool.git", branch = "main" }
# esmvalcore = { path = "../ESMValCore", editable = true }
# esmvaltool = { path = "../ESMValTool", editable = true }

[tool.pixi.feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-datadir = "*"
pytest-mock = "*"
pytest-xdist = "*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.py314.dependencies]
python = "3.14.*"


[tool.codespell]
ignore-words-list = "emac,oce,pres"
skip = "pixi.lock"


[tool.pytest.ini_options]
addopts = ["-ra", "--strict-config", "--strict-markers"]
minversion = "6.0"
xfail_strict = true


[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN401",     # Dynamically typed expressions (typing.Any) are disallowed
    "C901",       # Function is too complex
    "CPY001",     # Missing copyright notice at top of file
    "DTZ",        # Missing timezone information
    "G004",       # Logging statement uses f-string
    "PLR0912",    # Too many branches
    "PLR0913",    # Too many arguments in function definition
    "PLR0915",    # Too many statements
    "PLW2901",    # `for` loop variable overwritten by assignment target
]
future-annotations = true

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = [
    "ARG001",     # Unused function arguments
    "D100",       # Missing docstring in public module
    "D101",       # Missing docstring in public class
    "D102",       # Missing docstring in public method
    "D103",       # Missing docstring in public function
    "D104",       # Missing docstring in public package
    "FBT001",     # Boolean-typed positional argument in function definition
    "PLR0917",    # Too many positional arguments
    "S101",       # Use of `assert` detected
    "SLF001",     # Private member accessed
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
