###############################################################################
# ESMValTool configuration template for ICONEval
###############################################################################
---
auxiliary_data_dir: /work/bd0854/DATA/ESMValTool2/AUX
max_parallel_tasks: 4
projects:
  CMIP6:
    data:
      dkrz:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/ik1017/CMIP6/data
        dirname_template: "{project}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{version}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}*.nc"
      manuels-additional-data:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/b309141/additional_CMIP6
        dirname_template: "{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{version}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}*.nc"
      esgf-cache:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/download
        dirname_template: "{project}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{version}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}*.nc"
  CMIP5:
    data:
      dkrz:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/kd0956/CMIP5/data
        dirname_template: "{project.lower}/{product}/{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{version}/{short_name}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}*.nc"
      manuels-additional-data:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/b309141/additional_CMIP5
        dirname_template: "{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{version}/{short_name}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}*.nc"
      esgf-cache:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/download
        dirname_template: "{project.lower}/{product}/{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{version}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}*.nc"
  CMIP3:
    data:
      dkrz:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/CMIP3
        dirname_template: "{exp}/{modeling_realm}/{frequency}/{short_name}/{dataset}/{ensemble}"
        filename_template: "{short_name}_*.nc"
      esgf-cache:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/download
        dirname_template: "{project.lower}/{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{ensemble}/{short_name}/{version}"
        filename_template: "{short_name}_*.nc"
  CORDEX:
    data:
      dkrz:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/ik1017/C3SCORDEX/data/c3s-cordex/output
        dirname_template: "{domain}/{institute}/{driver}/{exp}/{ensemble}/{institute}-{dataset}/{rcm_version}/{mip}/{short_name}/{version}"
        filename_template: "{short_name}_{domain}_{driver}_{exp}_{ensemble}_{institute}-{dataset}_{rcm_version}_{mip}*.nc"
      esgf-cache:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/download
        dirname_template: "{project.lower}/output/{domain}/{institute}/{driver}/{exp}/{ensemble}/{dataset}/{rcm_version}/{frequency}/{short_name}/{version}"
        filename_template: "{short_name}_{domain}_{driver}_{exp}_{ensemble}_{institute}-{dataset}_{rcm_version}_{mip}*.nc"
  obs4MIPs:
    data:
      dkrz:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/OBS
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{short_name}_*.nc"
      esgf-cache:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/download
        dirname_template: "{project}/{dataset}/{version}"
        filename_template: "{short_name}_*.nc"
  ana4MIPs:
    data:
      dkrz:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/OBS
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{short_name}_{mip}_{type}_{dataset}_*.nc"
  native6:
    data:
      dkrz-obs:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/OBS
        dirname_template: "Tier{tier}/{dataset}/{version}/{frequency}/{short_name}"
        filename_template: "*.nc"
      dkrz-rawobs:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/RAWOBS
        dirname_template: "Tier{tier}/{dataset}/{version}/{frequency}/{short_name}"
        filename_template: "*.nc"
  OBS6:
    data:
      dkrz:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/OBS
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{project}_{dataset}_{type}_{version}_{mip}_{short_name}[_.]*nc"
  OBS:
    data:
      dkrz:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /work/bd0854/DATA/ESMValTool2/OBS
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{project}_{dataset}_{type}_{version}_{mip}_{short_name}[_.]*nc"

# CAP7-specific settings
projects:
  ICON:
    extra_facets:
      ICON-XPP:
        '*':
          # 2D atmosphere variables
          asr: {var_type: atm_2d}
          clivi: {raw_name: tqi_dia, var_type: atm_2d}
          clt: {raw_name: clct, var_type: atm_2d}
          clwvi: {var_type: atm_2d}
          evspsbl: {raw_name: qhfl_s, raw_units: kg m-2 s-1, var_type: atm_2d}
          hfls: {raw_name: lhfl_s, var_type: atm_2d}
          hfns: {var_type: atm_2d}
          hfss: {raw_name: shfl_s, var_type: atm_2d}
          lwcre: {var_type: atm_2d}
          lwp: {raw_name: tqc_dia, var_type: atm_2d}
          netcre: {var_type: atm_2d}
          pr: {raw_name: tot_prec_rate, var_type: atm_2d}
          prw: {raw_name: tqv_dia, var_type: atm_2d}
          ps: {raw_name: pres_sfc, var_type: atm_2d}
          psl: {raw_name: pres_msl, var_type: atm_2d}
          rlns: {raw_name: thb_s, var_type: atm_2d}
          rlut: {raw_name: thb_t, var_type: atm_2d}
          rlutcs: {raw_name: lwflx_up_clr, var_type: atm_2d}
          rsdt: {raw_name: sod_t, var_type: atm_2d}
          rsns: {raw_name: sob_s, var_type: atm_2d}
          rsnt: {raw_name: sob_t, var_type: atm_2d}
          rsus: {raw_name: sou_s, var_type: atm_2d}
          rsut: {raw_name: sou_t, var_type: atm_2d}
          rsutcs: {raw_name: swflx_up_clr, var_type: atm_2d}
          rtmt: {var_type: atm_2d}
          rtnt: {var_type: atm_2d}
          sfcWind: {raw_name: sp_10m, var_type: atm_2d}
          sftlf: {raw_name: fr_land, raw_units: '1', var_type: atm_2d}
          swcre: {var_type: atm_2d}
          tas: {raw_name: t_2m, var_type: atm_2d}
          tauu: {raw_name: umfl_s, var_type: atm_2d}
          tauv: {raw_name: vmfl_s, var_type: atm_2d}
          ts: {raw_name: t_s, var_type: atm_2d}

          # 3D atmosphere variables
          cl: {raw_name: clc, var_type: atm_3d}
          cli: {raw_name: tot_qi_dia, var_type: atm_3d}
          clw: {raw_name: tot_qc_dia, var_type: atm_3d}
          hur: {raw_name: rh, var_type: atm_3d}
          hus: {raw_name: qv, var_type: atm_3d}
          ta: {raw_name: temp, var_type: atm_3d}
          ua: {raw_name: u, var_type: atm_3d}
          va: {raw_name: v, var_type: atm_3d}
          wap: {raw_name: omega, var_type: atm_3d}
          zg: {raw_name: geopot, var_type: atm_3d}

          # 2D land variables
          gpp: {raw_name: assimi_gross_assimilation_box, var_type: jsb_2d_ml}
          lai: {raw_name: pheno_lai_box, var_type: jsb_2d_ml, raw_units: '1'}

          # 2D ocean variables
          hfds: {raw_name: HeatFlux_Total, var_type: oce_dbg}
          mlotst: {raw_name: mld, var_type: oce_dbg}
          siconc: {raw_name: conc, var_type: oce_ice, raw_units: '1'}
          siconca: {raw_name: fr_seaice, var_type: atm_2d}
          sithick: {raw_name: hi, var_type: oce_ice}
          sos: {var_type: oce_def, raw_units: "0.001"}
          tos: {raw_name: t_seasfc, var_type: atm_2d}
          zos: {raw_name: zos, var_type: oce_dbg}

          # 3D ocean variables
          so: {var_type: oce_def, raw_units: "0.001"}
          thetao: {raw_name: to, var_type: oce_def, raw_units: degC}
          uo: {raw_name: u, var_type: oce_def}
          vo: {raw_name: v, var_type: oce_def}
