---
name: Check coverage

permissions: {}

on:
  push:
    branches:
      - main
      - v*.x
  pull_request:
  schedule:
    - cron: 0 0 1 * *  # once per month

defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  check_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup environment
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          frozen: true
      - name: Run tests
        run: |
          pytest -n 2 --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov-report=term-missing:skip-covered --cov=iconeval tests/
      - name: Comment coverage
        id: coverage
        uses: MishaKav/pytest-coverage-comment@ce64cfb4332195faa36733a0364dda8849109f70 # v1.11.2
        with:
          coverage-path-prefix: src/iconeval/
          hide-comment: true
          junitxml-path: ./pytest.xml
          pytest-xml-coverage-path: ./coverage.xml
      - name: Check coverage
        run: |
          echo "Test coverage: ${STEPS_COVERAGE_OUTPUTS_COVERAGE} (target: 100%)"
          echo "${STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML}" >> ${GITHUB_STEP_SUMMARY}
          if [ "${STEPS_COVERAGE_OUTPUTS_COVERAGE}" == '100%' ]; then
            echo "Target coverage: 100% ✅" >> ${GITHUB_STEP_SUMMARY}
          else
            echo "Target coverage: 100% ❌" >> ${GITHUB_STEP_SUMMARY}
            exit 1
          fi
        env:
          STEPS_COVERAGE_OUTPUTS_COVERAGE: ${{ steps.coverage.outputs.coverage }}
          STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML: ${{ steps.coverage.outputs.coverageHtml }}
