---
name: Check coverage

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - v*.x
  pull_request:

defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  check_coverage:
    runs-on: ubuntu-latest
    name: Check coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup environment
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          frozen: true
      - name: Run tests
        run: |
          pytest -n 2 --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov-report=term-missing:skip-covered --cov=iconeval tests/
      - name: Comment coverage
        id: coverage
        uses: MishaKav/pytest-coverage-comment@fd9adbdca9fdfbe2b9bfa44a7340e6a83346ce6c # v1.10.0
        with:
          coverage-path-prefix: src/iconeval/
          hide-comment: true
          junitxml-path: ./pytest.xml
          pytest-xml-coverage-path: ./coverage.xml
      - name: Check coverage
        run: |
          echo "Test coverage: ${STEPS_COVERAGE_OUTPUTS_COVERAGE} (target: 100%)"
          echo "${STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML}" >> ${GITHUB_STEP_SUMMARY}
          if [ "${STEPS_COVERAGE_OUTPUTS_COVERAGE}" == '100%' ]; then
            echo "Target coverage: 100% ✅" >> ${GITHUB_STEP_SUMMARY}
          else
            echo "Target coverage: 100% ❌" >> ${GITHUB_STEP_SUMMARY}
            exit 1
          fi
        env:
          STEPS_COVERAGE_OUTPUTS_COVERAGE: ${{ steps.coverage.outputs.coverage }}
          STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML: ${{ steps.coverage.outputs.coverageHtml }}
