---
name: Check coverage

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - v*.x
  pull_request:

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: bash -l {0}

jobs:
  check_coverage:
    runs-on: ubuntu-latest
    name: Check coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          activate-environment: iconeval
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          use-mamba: true
      - name: Install ICONEval
        run: pip install --no-deps -e .[develop]
      - name: Run tests
        run: |
          pytest -n 2 --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov-report=term-missing:skip-covered --cov=iconeval tests/
      - name: Comment coverage
        id: coverage
        uses: MishaKav/pytest-coverage-comment@dd5b80bde6d16941f336518e92929e89069d8451 # v1.7.2
        with:
          coverage-path-prefix: iconeval/
          hide-comment: true
          junitxml-path: ./pytest.xml
          pytest-xml-coverage-path: ./coverage.xml
      - name: Check coverage
        run: |
          echo "Test coverage: ${STEPS_COVERAGE_OUTPUTS_COVERAGE} (target: 100%)"
          echo "${STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML}" >> ${GITHUB_STEP_SUMMARY}
          if [ "${STEPS_COVERAGE_OUTPUTS_COVERAGE}" == '100%' ]; then
            echo "Target coverage: 100% ✅" >> ${GITHUB_STEP_SUMMARY}
          else
            echo "Target coverage: 100% ❌" >> ${GITHUB_STEP_SUMMARY}
            exit 1
          fi
        env:
          STEPS_COVERAGE_OUTPUTS_COVERAGE: ${{ steps.coverage.outputs.coverage }}
          STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML: ${{ steps.coverage.outputs.coverageHtml }}
