---
name: Comment coverage in PRs

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  comment_coverage_in_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup environment
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          frozen: true
      - name: Run tests
        run: |
          pytest -n 2 --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov-report=term-missing:skip-covered --cov=iconeval tests/
      - name: Comment coverage
        uses: MishaKav/pytest-coverage-comment@fd9adbdca9fdfbe2b9bfa44a7340e6a83346ce6c # v1.10.0
        with:
          coverage-path-prefix: src/iconeval/
          junitxml-path: ./pytest.xml
          pytest-xml-coverage-path: ./coverage.xml
          report-only-changed-files: true
