---
name: Update Coverage Badge

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]

defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  update_badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup environment
        uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
        with:
          frozen: true
      - name: Run tests
        run: |
          pytest -n 2 --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov-report=term-missing --cov=iconeval tests/
      - name: Comment coverage
        id: coverage
        uses: MishaKav/pytest-coverage-comment@09c28b6767e12a048e0b23e821ed03133ee48a1a # v1.11.0
        with:
          coverage-path-prefix: src/iconeval/
          hide-comment: true
          junitxml-path: ./pytest.xml
          pytest-xml-coverage-path: ./coverage.xml
      - name: Update README
        run: |
          sed -i "/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n${STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML}\n<!-- Pytest Coverage Comment:End -->" ./README.md
        env:
          STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML: ${{ steps.coverage.outputs.coverageHtml }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: README.md
          base: main
          body: This pull request updates the coverage badge in README.md.
          branch: update-coverage-badge
          commit-message: Update coverage badge
          delete-branch: true
          labels: |
            auto pr
            documentation
          reviewers: schlunma
          title: Update coverage badge
